repos:
  - repo: local
    hooks:
      - id: ticket-number
        name: check for ticket ID in commit message
        language: pygrep
        entry: '\A(?!\[(DEV)-([0-9]+)\](.+))'
        args:
          - '--multiline'
        stages:
          - commit-msg
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - '--deep'
          - '--enable-rule=terraform_backend_warning'
          - '--enable-rule=terraform_deprecated_index'
          - '--enable-rule=terraform_deprecated_interpolation'
          - '--enable-rule=terraform_empty_list_equality'
          - '--enable-rule=terraform_module_version'
          - '--enable-rule=terraform_typed_variables'
