repos:
  - repo: local
    hooks:
      - id: terraform-validate
        name: terraform validate
        entry: terraform
        args:
          - validate
        language: system
        stages:
          - commit
      - id: terraform-fmt
        name: terraform fmt
        entry: terraform
        args:
          - fmt
          - -check=true
        language: system
        stages:
          - commit
